name: PR Merge Greeting

on:
  pull_request:
    types:
      - closed

jobs:
  greet:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Print Greeting
        run: echo "🎉 Hello! PR has been successfully merged. Welcome!"
